-- MySQL Script generated by MySQL Workbench
-- 09/14/15 10:39:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema custonix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema custonix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `custonix` ;
USE `custonix` ;

-- -----------------------------------------------------
-- Table `custonix`.`design`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`design` ;

CREATE TABLE IF NOT EXISTS `custonix`.`design` (
  `designid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `designname` VARCHAR(40) NOT NULL,
  `designdescription` TINYTEXT NULL,
  `designcol` VARCHAR(45) NULL,
  PRIMARY KEY (`designid`),
  UNIQUE INDEX `designname_UNIQUE` (`designname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custonix`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`user` ;

CREATE TABLE IF NOT EXISTS `custonix`.`user` (
  `userid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `encryptpassword` VARCHAR(90) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `usertype` ENUM('a', 'c', 'd') NOT NULL DEFAULT 'c' COMMENT 'where \'a\' is admin, \'c\' is customer amd \'d\' is designer',
  `firstname` VARCHAR(80) NOT NULL,
  `middlename` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `profilepicture` VARCHAR(90) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2000001;


-- -----------------------------------------------------
-- Table `custonix`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`category` ;

CREATE TABLE IF NOT EXISTS `custonix`.`category` (
  `categoryid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryname` VARCHAR(45) NOT NULL,
  `categorydescription` TINYTEXT NULL,
  PRIMARY KEY (`categoryid`),
  UNIQUE INDEX `categoryname_UNIQUE` (`categoryname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custonix`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`picture` ;

CREATE TABLE IF NOT EXISTS `custonix`.`picture` (
  `pictureid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `leftside` VARCHAR(90) NULL,
  `rightside` VARCHAR(90) NULL,
  `front` VARCHAR(90) NULL,
  `back` VARCHAR(90) NULL,
  `leftdescription` TINYTEXT NULL,
  `rightdescription` TINYTEXT NULL,
  `frontdescription` TINYTEXT NULL,
  `backdescription` TINYTEXT NULL,
  PRIMARY KEY (`pictureid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custonix`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`size` ;

CREATE TABLE IF NOT EXISTS `custonix`.`size` (
  `sizeid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sizename` VARCHAR(45) NOT NULL,
  `sizeinch` INT NOT NULL,
  `sizecm` INT NOT NULL,
  `size_sizeid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sizeid`),
  INDEX `fk_size_size1_idx` (`size_sizeid` ASC),
  CONSTRAINT `fk_size_size1`
    FOREIGN KEY (`size_sizeid`)
    REFERENCES `custonix`.`size` (`sizeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custonix`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`color` ;

CREATE TABLE IF NOT EXISTS `custonix`.`color` (
  `colorid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `colorhex` VARCHAR(6) NOT NULL,
  `part` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`colorid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custonix`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`items` ;

CREATE TABLE IF NOT EXISTS `custonix`.`items` (
  `itemid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemname` VARCHAR(40) NOT NULL,
  `categoryid` INT UNSIGNED NOT NULL,
  `qty` INT(4) NOT NULL DEFAULT 1,
  `pictureid` INT UNSIGNED NULL,
  `comment` TEXT(8) NULL,
  `shapeid` INT UNSIGNED NULL,
  `designid` INT UNSIGNED NULL,
  `datetofinish` DATETIME NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `size_sizeid` INT UNSIGNED NOT NULL,
  `color_colorid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`itemid`, `categoryid`),
  UNIQUE INDEX `itemname_UNIQUE` (`itemname` ASC),
  INDEX `itemscategory_idx` (`categoryid` ASC),
  INDEX `itemsdesign_idx` (`designid` ASC),
  INDEX `itemspicture_idx` (`pictureid` ASC),
  INDEX `fk_items_size1_idx` (`size_sizeid` ASC),
  INDEX `fk_items_color1_idx` (`color_colorid` ASC),
  CONSTRAINT `itemscategory`
    FOREIGN KEY (`categoryid`)
    REFERENCES `custonix`.`category` (`categoryid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `itemsdesign`
    FOREIGN KEY (`designid`)
    REFERENCES `custonix`.`design` (`designid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `itemspicture`
    FOREIGN KEY (`pictureid`)
    REFERENCES `custonix`.`picture` (`pictureid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_items_size1`
    FOREIGN KEY (`size_sizeid`)
    REFERENCES `custonix`.`size` (`sizeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_color1`
    FOREIGN KEY (`color_colorid`)
    REFERENCES `custonix`.`color` (`colorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8000001;


-- -----------------------------------------------------
-- Table `custonix`.`bid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`bid` ;

CREATE TABLE IF NOT EXISTS `custonix`.`bid` (
  `bidid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `itemid` INT UNSIGNED NOT NULL,
  `price` DECIMAL NOT NULL DEFAULT 100.00,
  `status` ENUM('1', '0') NOT NULL COMMENT '\'1\' selected and \'0\' is not selected',
  `date_started` DATETIME NOT NULL,
  `daystofinish` INT(3) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `userid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bidid`, `userid`, `itemid`),
  INDEX `biditems_idx` (`itemid` ASC),
  INDEX `fk_bid_user1_idx` (`userid` ASC),
  CONSTRAINT `biditems`
    FOREIGN KEY (`itemid`)
    REFERENCES `custonix`.`items` (`itemid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `bid_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `custonix`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `custonix`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custonix`.`contact` ;

CREATE TABLE IF NOT EXISTS `custonix`.`contact` (
  `contactid` INT UNSIGNED NOT NULL,
  `userid` INT UNSIGNED NOT NULL,
  `contactno` VARCHAR(45) NULL,
  INDEX `usercotact_idx` (`userid` ASC),
  PRIMARY KEY (`contactid`),
  CONSTRAINT `usercotact`
    FOREIGN KEY (`userid`)
    REFERENCES `custonix`.`user` (`userid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `contactcontact`
    FOREIGN KEY (`contactid`)
    REFERENCES `custonix`.`contact` (`contactid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `custonix` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `custonix`;
DROP  IF EXISTS `custonix`.`routine1`;

DELIMITER $$
USE `custonix`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
